import { lcskPlusPlus } from "./LCSKPlusPlus";

// const seqA = <"GTCGAACGGGAATCAGTTAGGCGACCACGTTCCAGCCGTGGAATCAGTCGTCGACAAGTTCATATGGATTTTCCTCCTTTACTTGAGTAAGGCCAATGAT";
// const seqB = "CAGAACCGCCGGACAGGCGTCTTCCTGAATAATCCGTCATTGCGTCGAATAGCATGCGGGTAGTACAAAAACGCAGAGATCGACCTTCGGTAGCATGTAG";

//const out = lcskPlusPlus(seqA, seqB, 2);
const out = lcskPlusPlus("ABCGGAB", "ABCBA", 2);
console.log(out);
